config/routes.rb
Rails.application.routes.draw do
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]  
  get 'static_pages/privacy_policy'
  get 'static_pages/about_us'
  get 'static_pages/disclaimer'
  get 'static_pages/terms_and_conditions'

  get "system/*path", to: redirect("/", status: 301)
  get "pictures", to: redirect("/", status: 301)
  get "pictures/*path", to: redirect("/", status: 301)
  get "quote-of-the-day", to: redirect("/", status: 301)
  get "quote-of-the-day/*path", to: redirect("/", status: 301)
  get "authors", to: redirect("/people", status: 301)
  get "authors/:slug", to: redirect("/people/%{slug}", status: 301)
  get "authors/:slug/:page", to: redirect("/people/%{slug}/%{page}", status: 301)

  devise_for :users, path: "my", controllers: {omniauth_callbacks: "my/omniauth_callbacks"}
  devise_scope :user do
    get 'login', :to => 'my/sessions#new', :as => :new_user_session
    get 'logout', :to => 'my/sessions#destroy', :as => :destroy_user_session
  end
  
  devise_for :admins, path: "admin", path_names: {sign_in: "login", sign_out: "logout"}, controllers: {sessions: "admin/sessions"}

  resources :people, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get ':featured_topic', action: 'featured_topic', as: 'featured_topic', featured_topic: /on-.+/, format: true
      get 'facebook'
      get 'pinterest'
      get 'twitter'
      get 'google_plus'
      get ':redirect_to_person', action: 'redirect_to_person', constraints: { page: /\D+/ }
    end
  end

  resources :proverbs, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end
    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get ':featured_topic', action: 'featured_topic', as: 'featured_topic', featured_topic: /on-.+/, format: true
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
      get ':redirect_to_proverb', action: 'redirect_to_proverb', constraints: { page: /\D+/ }
    end
  end

  resources :books, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
      get ':redirect_to_book', action: 'redirect_to_book', constraints: { page: /\D+/ }
    end
  end

  namespace :topics do
    resources :topic_combinations, path: "combinations", only: [:index, :show] do
      member do
        get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
        get 'pinterest'
        get 'facebook'
        get 'twitter'
        get 'google_plus'
      end
    end
  end

  resources :topics, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :movies, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :tv_shows, only: [:index, :show], path: "tv-shows" do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :characters, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :quotes, only: [] do
    member do
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :messages, path: "contact-us", only: [:new, :create] do
    collection do
      get "success", action: "success", as: "success"
    end
  end
  resources :subscribers, only: [:create]

  get 'feed' => 'welcome#feed', :as => :feed
  get 'privacy-policy' => 'static_pages#privacy_policy', as: :privacy_policy
	get 'about-us' => 'static_pages#about_us', as: :about_us
	get 'disclaimer' => 'static_pages#disclaimer', as: :disclaimer
	get 'terms-and-conditions' => 'static_pages#terms_and_conditions', as: :terms_and_conditions

  get "/404" => "exceptions#serve_404", as: "serve_404"

  get "/500" => "exceptions#serve_500"

  root 'welcome#index'

  namespace :admin do
    root 'dashboard#index'
    get "regenerate-social-images" => "dashboard#regenerate_social_images", as: :regenerate_social_images
    get "regenerate-quote-images" => "dashboard#regenerate_quote_images", as: :regenerate_quote_images
    
    resources :users, only: [:index, :destroy]
    resources :subscribers, only: [:index, :destroy]
    
    resources :quotes do
      member do
        get "verify"
        get "tweetable"
        get "image"
      end
    end
    resources :people do
      member do
        get "review"
        get ':featured_topic', action: 'featured_topic', as: 'featured_topic', featured_topic: /on-.*/
      end
    end
    resources :books do
      member do
        get "review"
      end
    end
    resources :movies do
      member do
        get "review"
      end
    end
    resources :proverbs do
      member do
        get "review"
      end
    end
    resources :tv_shows, path: "tv-shows" do
      member do
        get "review"
      end
    end
    resources :characters do
      member do
        get "review"
      end
    end

    resources :featured_topics
    resources :topics do
      member do
        get "review"
      end
      resources :topic_aliases
    end
    resources :topic_combinations, only: [:index, :show], path: "topic-combinations"
    resources :quote_topic_suggestions, only: [:index], path: "quote-topic-suggestions" do
      member do
        get 'accept', as: 'accept'
        get 'decline', as: 'decline'
      end
    end
    resources :tweetable_quotes, path: "tweetable-quotes", only: [:index, :destroy]
    resources :quote_of_the_days, path: "quote-of-the-day", only: [:index]
    resources :color_schemes, path: "color-schemes"
    resources :messages, only: [:index, :show, :destroy]
    resources :logs, only: [:index, :destroy]
    resources :redirects, except: [:show]
    resources :settings
    resources :nationalities
    resources :professions
  end

  namespace :my do
    root "dashboard#index"
    get "mark-for-deletion" => "dashboard#mark_for_deletion", as: :account_mark_for_deletion
    get "unmark-for-deletion" => "dashboard#unmark_for_deletion", as: :account_unmark_for_deletion
    resources :user_lists, path: "lists"
    resources :user_quotes, path: "quotes", except: [:show]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def privacy_policy
  end

  def about_us
  end

  def disclaimer
  end

  def terms_and_conditions
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about_us.html.erb
<h1>StaticPages#about_us</h1>
<p>Find me in app/views/static_pages/about_us.html.erb</p>

app/views/static_pages/disclaimer.html.erb
<% content_for :title do %>Website Disclaimer | LoveAQuote<% end %>

<% content_for :description do %>Website Disclaimer for LoveAQuote<% end %>

<% content_for :canonical do %><%= disclaimer_url %><% end %>

<% content_for :heading do %>LoveAQuote Disclaimer<% end %>

<% content_for :content do %>
<div class="col-xs-12">
    <h1 class="no-top-margin text-center">Disclaimer</h1>
    <p>LoveAQuote is not responsible for, and expressly disclaims all liability for, damages of any kind arising out of use, reference to, or reliance on any information contained within the site. While the information contained within the site is periodically updated, no guarantee is given that the information provided in this Web site is correct, complete, and up-to-date.</p>
    <p>Although the LoveAQuote website may include links providing direct access to other Internet resources, including Web sites, LoveAQuote is not responsible for the accuracy or content of information contained in these sites.</p>
    <p>Links from LoveAQuote to third-party sites do not constitute an endorsement by LoveAQuote of the parties or their products and services. The appearance on the website of advertisements and product or service information does not constitute an endorsement by LoveAQuote, and LoveAQuote has not investigated the claims made by any advertiser. Product information is based solely on material received from suppliers.    
</div>
<% end %>

<% content_for :additional_tags do %>
  <meta name="robots" content="noindex,follow">
<% end %>

app/views/static_pages/privacy_policy.html.erb
<% content_for :title do %>Privacy policy | LoveAQuote<% end %>

<% content_for :description do %>Privacy policy for LoveAQuote<% end %>

<% content_for :canonical do %><%= privacy_policy_url %><% end %>

<% content_for :heading do %>LoveAQuote Privacy Policy<% end %>

<% content_for :content do %>
<div class="col-xs-12">
    <h1 class="no-top-margin text-center">Privacy Policy</h1>
    <p>This Privacy Policy governs the manner in which LoveAQuote collects, uses, maintains and discloses information collected from users (each, a "User") of the http://www.loveaquote.com website ("Site"). This privacy policy applies to the Site and all products and services offered by LoveAQuote.</p>
    
    <strong>Personal identification information</strong>
    <p>We may collect personal identification information from Users in a variety of ways, including, but not limited to, when Users visit our site, register on the site, subscribe to the newsletter, fill out a form, and in connection with other activities, services, features or resources we make available on our Site. Users may be asked for, as appropriate, name, email address. Users may, however, visit our Site anonymously. We will collect personal identification information from Users only if they voluntarily submit such information to us. Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain Site related activities.</p>
    <strong>Non-personal identification information</strong>
    <p>We may collect non-personal identification information about Users whenever they interact with our Site. Non-personal identification information may include the browser name, the type of computer and technical information about Users means of connection to our Site, such as the operating system and the Internet service providers utilized and other similar information.</p>
    <strong>Web browser cookies</strong>
    <p>Our Site may use "cookies" to enhance User experience. User's web browser places cookies on their hard drive for record-keeping purposes and sometimes to track information about them. User may choose to set their web browser to refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of the Site may not function properly.</p>
    <strong>How we use collected information</strong>
    <p>LoveAQuote may collect and use Users personal information for the following purposes:</p>
    <ul>
    <li>To improve customer service</li>
    Information you provide helps us respond to your customer service requests and support needs more efficiently.
    <p></p>
    <li>To personalize user experience</li>
    <p>We may use information in the aggregate to understand how our Users as a group use the services and resources provided on our Site.</p>
    <li>To improve our Site</li>
    <p>We may use feedback you provide to improve our products and services.</p>
    <li>To send periodic emails</li>
    <p>If User decides to opt-in to our mailing list, they will receive emails that may include company news, updates, related product or service information, etc. If at any time the User would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email or User may contact us via our Site.</p>
    </ul>
    <strong>How we protect your information</strong>
    <p>We adopt appropriate data collection, storage and processing practices and security measures to protect against unauthorized access, alteration, disclosure or destruction of your personal information, username, password, transaction information and data stored on our Site.</p>
    <strong>Sharing your personal information</strong>
    <p>We do not sell, trade, or rent Users personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates and advertisers for the purposes outlined above.We may use third party service providers to help us operate our business and the Site or administer activities on our behalf, such as sending out newsletters or surveys. We may share your information with these third parties for those limited purposes provided that you have given us your permission.</p>
    <strong>Third party websites</strong>
    <p>Users may find advertising or other content on our Site that link to the sites and services of our partners, suppliers, advertisers, sponsors, licensors and other third parties. We do not control the content or links that appear on these sites and are not responsible for the practices employed by websites linked to or from our Site. In addition, these sites or services, including their content and links, may be constantly changing. These sites and services may have their own privacy policies and customer service policies. Browsing and interaction on any other website, including websites which have a link to our Site, is subject to that website's own terms and policies.</p>
    <strong>Advertising</strong>
    <p>Ads appearing on our site may be delivered to Users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile non personal identification information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This privacy policy does not cover the use of cookies by any advertisers. You can opt out of some third-party vendor's use of cookies for interest-based advertising by visiting <a href="http://www.aboutads.info/">aboutads.info.</a></p>
    <strong>Google Adsense</strong>
    <p>Some of the ads on this website may be served by Google. Google, as a third party vendor, uses cookies to serve ads on this website. Google's use of the DART cookie enables it to serve ads to Users based on their visit to our Site and other sites on the Internet. You may opt out of the use of the DART cookie for interest-based advertising by visiting <a href="https://www.google.com/settings/u/0/ads">Ads Settings</a></p>
    <strong>Changes to this privacy policy</strong>
    <p>LoveAQuote has the discretion to update this privacy policy at any time. When we do, we will revise the updated date at the bottom of this page. We encourage Users to frequently check this page for any changes to stay informed about how we are helping to protect the personal information we collect. You acknowledge and agree that it is your responsibility to review this privacy policy periodically and become aware of modifications.</p>
    <strong>Your acceptance of these terms</strong>
    <p>By using this Site, you signify your acceptance of this policy. If you do not agree to this policy, please do not use our Site. Your continued use of the Site following the posting of changes to this policy will be deemed your acceptance of those changes.</p>
    <strong>Contacting us</strong>
    <p>If you have any questions about this Privacy Policy, the practices of this site, or your dealings with this site, please contact us at:</p>
    <br>
    <%= link_to "LoveAQuote", root_url %>
    <br>
    <%= link_to "http://www.loveaquote.com", root_url %>
    <br><br>
    1503, Sector 17C
    Gurgaon, Haryana - 122001
    <br>
    +91-8396003838
    <br>
    dpk@loveaquote.com
    <br>
    <br>
    This document was last updated on March 4, 2016
</div>
<% end %>

<% content_for :additional_tags do %>
  <meta name="robots" content="noindex,follow">
<% end %>

app/views/static_pages/terms_and_conditions.html.erb
<% content_for :title do %>Terms and Conditions | LoveAQuote<% end %>

<% content_for :description do %>Terms and Conditions for LoveAQuote<% end %>

<% content_for :canonical do %><%= terms_and_conditions_url %><% end %>

<% content_for :heading do %>LoveAQuote Terms and Conditions<% end %>

<% content_for :content do %>
<div class="col-xs-12">
    <h1 class="no-top-margin text-center">Terms and Conditions</h1>
    <p>This document constitutes a legally-binding agreement ("Agreement") governing the terms of providing you with our service. Throughout this document, the words "LoveAQuote", "LoveAQuote.com", "us", "we", and "our", refer to us, LoveAQuote, or our website, LoveAQuote.com as is appropriate in the context of the use of the words.</p>
    
    <p>Likewise, the words "you" and "your" refer to you, the person who is being presented with this document for your agreement.</p>
    
    <strong>Description of Service</strong>
    <p>LoveAQuote, The Quote Lover's Community, offers a free access to our collections of Quotes and Proverbs. We collect these Quotes and Proverbs very diligently from various sources like Digital Archives, Newspapers, Magazines, and Books to name a few. All our quotes are hand picked and reviewed by a human being before they are published.
    </p>
    <p>Some of the quotes and proverbs may be soft edited for grammatical errors, spellings etc. without causing any change in the meaning or intent.</p>
    <p>We strive for accuracy but cannot be held responsible for any errors in quotations or incorrect attributions. Some quotations may include content considered inappropriate by some standards for some age groups. We take no responsibility for filtering content based on any standards of morality, religion, or politics.
    </p>
    
    <strong>Copyright</strong>
    <ul>
    <br>
    <li>Copyright of Quotes & Proverbs used on LoveAQuote</li>
    <p>All quotes and proverbs used on LoveAQuote remain the intellectual property of their respective originators. We do not assert any claim of copyright over these quotes and proverbs. By quoting we do not in any way mean to imply their endorsement or approval of our site or its contents. To the best of our knowledge, all quotes and proverbs included here fall under the fair use or public domain guidelines of copyright law. If you believe that any quotation violates a copyright you hold or represent, we will immediately remove it upon notification pending good-faith resolution of any dispute.</p>
    <li>Copyright of Images used on LoveAQuote</li>
    <p>Sometimes we use an image of the Author or the Book from which the quotes and proverbs have been sourced. The use of the image is to make the attribution of the quote to its source more prominent and for a better visual representation. To the best of our knowledge, all images used on LoveAQuote are either in public domain or are copyright free. If you believe that any image violates a copyright you hold or represent, we will immediately remove it upon notification pending good-faith resolution of any dispute.</p>
    <li>Our Copyright</li>
    <p>We assert a claim of copyright for our compilations of quotes and proverbs, their unique scope and style, our site design and look and feel. You are free to use the information that we provide on LoveAQuote.com for legitimate academic, research, and reporting projects, but you can't just copy and paste our stuff on your own website</p>
    </ul>
    <strong>LoveAQuote Privacy Polivy</strong>
    <p>To review the LoveAQuote Privacy Policy, please <%= link_to "click here", privacy_policy_url %>.</p>
    <strong>LoveAQuote Disclaimer</strong>
    <p>To review the LoveAQuote Disclaimer, please <%= link_to "click here", disclaimer_url %>.</p>
    <br>
    <%= link_to "LoveAQuote", root_url %>
    <br>
    <%= link_to "http://www.loveaquote.com", root_url %>
    <br><br>
    1503, Sector 17C
    Gurgaon, Haryana - 122001
    <br>
    +91-8396003838
    <br>
    dpk@loveaquote.com
    <br>
    <br>
    This document was last updated on March 4, 2016    
</div>
<% end %>

<% content_for :additional_tags do %>
  <meta name="robots" content="noindex,follow">
<% end %>