config/routes.rb
Rails.application.routes.draw do
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]  
  get 'static_pages/privacy_policy'
  get 'static_pages/about_us'
  get 'static_pages/disclaimer'
  get 'static_pages/terms_and_conditions'

  get "system/*path", to: redirect("/", status: 301)
  get "pictures", to: redirect("/", status: 301)
  get "pictures/*path", to: redirect("/", status: 301)
  get "quote-of-the-day", to: redirect("/", status: 301)
  get "quote-of-the-day/*path", to: redirect("/", status: 301)
  get "authors", to: redirect("/people", status: 301)
  get "authors/:slug", to: redirect("/people/%{slug}", status: 301)
  get "authors/:slug/:page", to: redirect("/people/%{slug}/%{page}", status: 301)

  devise_for :users, path: "my", controllers: {omniauth_callbacks: "my/omniauth_callbacks"}
  devise_scope :user do
    get 'login', :to => 'my/sessions#new', :as => :new_user_session
    get 'logout', :to => 'my/sessions#destroy', :as => :destroy_user_session
  end
  
  devise_for :admins, path: "admin", path_names: {sign_in: "login", sign_out: "logout"}, controllers: {sessions: "admin/sessions"}

  resources :people, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get ':featured_topic', action: 'featured_topic', as: 'featured_topic', featured_topic: /on-.+/, format: true
      get 'facebook'
      get 'pinterest'
      get 'twitter'
      get 'google_plus'
      get ':redirect_to_person', action: 'redirect_to_person', constraints: { page: /\D+/ }
    end
  end

  resources :proverbs, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end
    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get ':featured_topic', action: 'featured_topic', as: 'featured_topic', featured_topic: /on-.+/, format: true
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
      get ':redirect_to_proverb', action: 'redirect_to_proverb', constraints: { page: /\D+/ }
    end
  end

  resources :books, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
      get ':redirect_to_book', action: 'redirect_to_book', constraints: { page: /\D+/ }
    end
  end

  namespace :topics do
    resources :topic_combinations, path: "combinations", only: [:index, :show] do
      member do
        get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
        get 'pinterest'
        get 'facebook'
        get 'twitter'
        get 'google_plus'
      end
    end
  end

  resources :topics, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :movies, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :tv_shows, only: [:index, :show], path: "tv-shows" do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :characters, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :quotes, only: [] do
    member do
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :messages, path: "contact-us", only: [:new, :create] do
    collection do
      get "success", action: "success", as: "success"
    end
  end
  resources :subscribers, only: [:create]

  get 'feed' => 'welcome#feed', :as => :feed
  get 'privacy-policy' => 'static_pages#privacy_policy', as: :privacy_policy
	get 'about-us' => 'static_pages#about_us', as: :about_us
	get 'disclaimer' => 'static_pages#disclaimer', as: :disclaimer
	get 'terms-and-conditions' => 'static_pages#terms_and_conditions', as: :terms_and_conditions

  get "/404" => "exceptions#serve_404", as: "serve_404"

  get "/500" => "exceptions#serve_500"

  root 'welcome#index'

  namespace :admin do
    root 'dashboard#index'
    get "regenerate-social-images" => "dashboard#regenerate_social_images", as: :regenerate_social_images
    get "regenerate-quote-images" => "dashboard#regenerate_quote_images", as: :regenerate_quote_images
    
    resources :users, only: [:index, :destroy]
    resources :subscribers, only: [:index, :destroy]
    
    resources :quotes do
      member do
        get "verify"
        get "tweetable"
        get "image"
      end
    end
    resources :people do
      member do
        get "review"
        get ':featured_topic', action: 'featured_topic', as: 'featured_topic', featured_topic: /on-.*/
      end
    end
    resources :books do
      member do
        get "review"
      end
    end
    resources :movies do
      member do
        get "review"
      end
    end
    resources :proverbs do
      member do
        get "review"
      end
    end
    resources :tv_shows, path: "tv-shows" do
      member do
        get "review"
      end
    end
    resources :characters do
      member do
        get "review"
      end
    end

    resources :featured_topics
    resources :topics do
      member do
        get "review"
      end
      resources :topic_aliases
    end
    resources :topic_combinations, only: [:index, :show], path: "topic-combinations"
    resources :quote_topic_suggestions, only: [:index], path: "quote-topic-suggestions" do
      member do
        get 'accept', as: 'accept'
        get 'decline', as: 'decline'
      end
    end
    resources :tweetable_quotes, path: "tweetable-quotes", only: [:index, :destroy]
    resources :quote_of_the_days, path: "quote-of-the-day", only: [:index]
    resources :color_schemes, path: "color-schemes"
    resources :messages, only: [:index, :show, :destroy]
    resources :logs, only: [:index, :destroy]
    resources :redirects, except: [:show]
    resources :settings
    resources :nationalities
    resources :professions
  end

  namespace :my do
    root "dashboard#index"
    get "mark-for-deletion" => "dashboard#mark_for_deletion", as: :account_mark_for_deletion
    get "unmark-for-deletion" => "dashboard#unmark_for_deletion", as: :account_unmark_for_deletion
    resources :user_lists, path: "lists"
    resources :user_quotes, path: "quotes", except: [:show]
  end
end

app/models/color_scheme.rb
class ColorScheme < ActiveRecord::Base
    validates :background_color, presence: true, blank: false
    
    validates_uniqueness_of :background_color, scope: :foreground_color
    
    before_validation :add_foreground_color
    before_save :clean_up
    
    def add_foreground_color
        self.foreground_color = "FFFFFF" if self.foreground_color.blank?
    end
    
    def clean_up
        self.foreground_color = self.foreground_color[1..-1] if self.foreground_color[0] == "#"
        self.background_color = self.background_color[1..-1] if self.background_color[0] == "#"
    end
end

app/controllers/admin/color_schemes_controller.rb
class Admin::ColorSchemesController < ApplicationController
  before_filter :authenticate_admin!
  before_action :set_color_scheme, only: [:show, :edit, :update, :destroy]

  # GET /color_schemes
  # GET /color_schemes.json
  def index
    @color_schemes = ColorScheme.order(created_at: :DESC)
  end

  # GET /color_schemes/1
  # GET /color_schemes/1.json
  def show
  end

  # GET /color_schemes/new
  def new
    @color_scheme = ColorScheme.new
  end

  # GET /color_schemes/1/edit
  def edit
  end

  # POST /color_schemes
  # POST /color_schemes.json
  def create
    @color_scheme = ColorScheme.new(color_scheme_params)

    respond_to do |format|
      if @color_scheme.save
        format.html { redirect_to admin_color_schemes_url, notice: 'Color Scheme was successfully created.' }
        format.json { render :show, status: :created, location: @color_scheme }
      else
        format.html { render :new }
        format.json { render json: @color_scheme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /color_schemes/1
  # PATCH/PUT /color_schemes/1.json
  def update
    respond_to do |format|
      if @color_scheme.update(color_scheme_params)
        format.html { redirect_to admin_color_schemes_url, notice: 'Color Scheme was successfully updated.' }
        format.json { render :show, status: :ok, location: @color_scheme }
      else
        format.html { render :edit }
        format.json { render json: @color_scheme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /color_schemes/1
  # DELETE /color_schemes/1.json
  def destroy
    @color_scheme.destroy
    respond_to do |format|
      format.html { redirect_to admin_color_schemes_url, notice: 'color_scheme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color_scheme
      @color_scheme = ColorScheme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def color_scheme_params
      params.require(:color_scheme).permit(:background_color, :foreground_color)
    end
end

app/helpers/color_schemes_helper.rb
module ColorSchemesHelper
end

app/views/admin/color_schemes/_form.html.erb
<%= simple_form_for([:admin, @color_scheme]) do |f| %>
  <div class="row">
    <div class="col-sm-9">
      <div class="panel minimal minimal-gray">
        <div class="panel-heading">
          <div class="panel-title">
            
          </div>
          <div class="panel-options">
            <ul class="nav nav-tabs">
              <li class="active"><a href="#color-scheme" data-toggle="tab">Color Scheme</a></li>
            </ul>
          </div>
        </div>
        
        <div class="panel-body">
          <div class="tab-content">
            <div class="tab-pane active" id="color-scheme">
              <div class="form-inputs">
                <%= f.input :background_color %>
                <%= f.input :foreground_color %>
              </div>
            </div>
          </div>
        </div>
      </div>  
    </div>  

    <div class="col-sm-3 text-center">
      <% if @color_scheme.errors.any? %>
        <div class="alert alert-danger">
          <%= "#{@color_scheme.errors.count} error found" %>
        </div>
      <% end %>
      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    </div>
  </div>  
<% end %>

app/views/admin/color_schemes/edit.html.erb
<% content_for :content do %>
<div class="col-sm-12">
    <h2>Edit <%= link_to "color scheme", admin_color_scheme_url(@color_scheme), class: "btn btn-default dtn-sm" %> <%= link_to "color schemes", admin_color_schemes_url, class: "btn btn-default dtn-sm" %></h2>
    <%= render 'form' %>
</div>
<% end %>

app/views/admin/color_schemes/index.html.erb
<% content_for :content do %>
<div class="col-sm-12">
  
  <h2 style="margin-top: 0px">Color Scheme <%= link_to "add new", new_admin_color_scheme_url, class: "btn btn-default btn-sm" %></h2>
  
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th width="90%" class="text-center">Color Scheme</th>
        <th width="10%" class="text-center" colspan="2">Manage</th>
      </tr>
    </thead>
  
    <tbody>
      <% @color_schemes.each do |color_scheme| %>
        <tr>
          <td class="text-center" style="color: <%= "##{color_scheme.foreground_color}" %>;background-color: <%= "##{color_scheme.background_color}"%>">Color Scheme</td>
          <td class="text-center" style="vertical-align: middle"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_admin_color_scheme_url(color_scheme) %></td>
          <td class="text-center" style="vertical-align: middle"><%= link_to '<i class="fa fa-times"></i>'.html_safe, admin_color_scheme_url(color_scheme) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/admin/color_schemes/new.html.erb
<% content_for :content do %>
<div class="col-sm-12">
    <h2>Add New <%= link_to "back", admin_color_schemes_url, class:"btn btn-sm btn-default" %></h2>
    <%= render 'form' %>
</div>
<% end %>

app/views/admin/color_schemes/show.html.erb
<% content_for :content do %>
<div class="col-sm-12">
  <ol class="breadcrumb bc-3"> 
    <li><%= link_to "Home", admin_root_url %></li>
    <li><%= link_to "Books", admin_books_url %></li> 
    <li class="active"><%= @book.name %></li>
  </ol>
  
  <div class="row">
    <div class="col-sm-9">
      
      <div class="row">
        <div class="col-sm-3">
          <% if @book.image.present? %>
            <%= image_tag @book.image_url(:small), class: "thumbnail", style: "margin-bottom: 0px" %>
          <% else %>
            <%= image_tag "http://placehold.it/150x150", class: "thumbnail" %>
          <% end %>
        </div>
        <div class="col-sm-9">
          <h2 class="text-right"><%= link_to "view", book_url(@book), class: "btn btn-primary btn-sm", target: "_blank" %> <%= link_to "edit", edit_admin_book_url(@book), class: "btn btn-blue btn-sm" %> <%= link_to "new quote", "", class: "btn btn-default btn-sm add_new_quote" %> <%= @book.name %></h2>
          <h4 class="text-right"><em>by</em> <%= link_to @book.person.name, admin_person_url(@book.person) %></h4>
        </div>
      </div>
  
      <div class="panel minimal minimal-gray">
        <div class="panel-heading">
          <div class="panel-title">
            
          </div>
          <div class="panel-options">
            <ul class="nav nav-tabs">
              <li class="active">
                <a href="#quotes" data-toggle="tab">Quotes</a>
              </li>
              <li>
                <a href="#quote-topic-suggestions" data-toggle="tab">Topic Suggestions</a>
              </li>
            </ul>
          </div>
        </div>
        
        <div class="panel-body">
          
          <div class="tab-content">
            
            <div class="tab-pane active" id="quotes">
              <table class="table table-striped table-bordered table-hover">
                <thead>
                  <% if @book.characters.any? %>
                    <th width="5%" class="text-center">Verified</th>
                    <th width="65%" class="text-center">Quote</th>
                    <th width="20%" class="text-center">Character</th>
                  <% else %>
                    <th width="5%" class="text-center">Verified</th>
                    <th width="85%" class="text-center">Quote</th>
                  <% end %>
                  <th width="10%" class="text-center" colspan="2">Manage</th>
                </thead>
                
                <tbody>
                  <% @book.quotes.order(text: :asc).each do |quote| %>  
                  <tr>
                    <td class="text-center"><%= quote.chapter_and_page.present? ? '<i class="e-icon-check"></i>'.html_safe : '<i class="e-icon-cross"></i>'.html_safe %></td>
                    <td><%= quote.text %></td>
                    <% if @book.characters.any? %>
                      <td><%= link_to quote.character.name, admin_character_path(quote.character) if quote.character.present? %></td>
                    <% end %>
                    <td class="text-center"><%= link_to "Edit", edit_admin_quote_url(quote), target: "_blank", class: "btn btn-primary btn-xs" %></td>
                    <td class="text-center"><%= link_to "Delete", admin_quote_url(quote), method: :delete, remote: true, class: "delete-quote btn btn-red btn-xs" %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            
            <div class="tab-pane" id="quote-topic-suggestions">
              <div class="row">
                <table class="table table-striped table-bordered table-hover">
                  <thead>
                    <tr>
                      <th width="60%" class="text-center">Quote</th>
                      <th width="20%" class="text-center">Topic</th>
                      <th width="20%" class="text-center" colspan="2">Manage</th>
                    </tr>
                  </thead>
                
                  <tbody>
                    <% @book.quote_topic_suggestions.where(read: false).each do |quote_topic_suggestion| %>
                      <tr>
                        <td><%= quote_topic_suggestion.quote.text %></td>
                        <td class="text-center"><%= quote_topic_suggestion.topic.name %></td>
                        <td class="text-center"><%= link_to "Accept", accept_admin_quote_topic_suggestion_url(id: quote_topic_suggestion.id), class:"accept_suggestion", remote: true %></td>
                        <td class="text-center"><%= link_to "Decline", decline_admin_quote_topic_suggestion_url(id: quote_topic_suggestion.id), class:"decline_suggestion", remote: true %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>          
            </div>
            
          </div>
        </div>
      </div>
    </div>
    
    <div class="col-sm-3">
      <% if @book.characters.any? %>
        <div class="panel panel-default panel-shadow">
          <div class="panel-heading">
            <div class="panel-title">
              <h4>Characters</h4>
            </div>
          </div>
          <div class="panel-body">
            <ul>
              <% @book.characters.each do |character| %>
                <li><%= link_to character.name, admin_character_path(character) %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>  
</div>

<div class="modal fade in" id="new-quote-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Edit Quote</h4>
      </div>
      <div class="modal-body">
        <% @new_quote = Quote.new %>
        <% @new_quote.build_chapter_and_page %>
        <%= simple_form_for([:admin, @new_quote]) do |f| %>
          <div class="form-inputs">          
            <%= f.input :text, input_html: {rows: 5} %>
            <%= f.association :character, collection: @book.characters.order(name: :asc) if @book.characters.any? %>
            <%= f.simple_fields_for :chapter_and_page do |cap| %>
              <%= cap.input :chapter %>
              <%= cap.input :page %>
            <% end %>
            <%= f.hidden_field :source_id, value: @book.id %>
            <%= f.hidden_field :source_type, value: @book.class.name %>
          </div>
          <div class="form-actions">
            <%= f.button :submit %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    $(".accept_suggestion")
    .on("ajax:complete", function(e, data, status, xhr) {
        $(this).closest("tr").remove();
    });
  
    $(".decline_suggestion")
    .on("ajax:complete", function(e, data, status, xhr) {
        $(this).closest("tr").remove();
    });
    
    $(".add_new_quote").on("click", function(e) {
      e.preventDefault();
      $("#new-quote-modal").modal('show');
    });
    
    $(".delete-quote").on("ajax:complete", function(xhr, status) {
      $(this).closest("tr").remove();
    });
  });
</script>
<% end %>