config/routes.rb
Rails.application.routes.draw do
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]  
  get 'static_pages/privacy_policy'
  get 'static_pages/about_us'
  get 'static_pages/disclaimer'
  get 'static_pages/terms_and_conditions'

  get "system/*path", to: redirect("/", status: 301)
  get "pictures", to: redirect("/", status: 301)
  get "pictures/*path", to: redirect("/", status: 301)
  get "quote-of-the-day", to: redirect("/", status: 301)
  get "quote-of-the-day/*path", to: redirect("/", status: 301)
  get "authors", to: redirect("/people", status: 301)
  get "authors/:slug", to: redirect("/people/%{slug}", status: 301)
  get "authors/:slug/:page", to: redirect("/people/%{slug}/%{page}", status: 301)

  devise_for :users, path: "my", controllers: {omniauth_callbacks: "my/omniauth_callbacks"}
  devise_scope :user do
    get 'login', :to => 'my/sessions#new', :as => :new_user_session
    get 'logout', :to => 'my/sessions#destroy', :as => :destroy_user_session
  end
  
  devise_for :admins, path: "admin", path_names: {sign_in: "login", sign_out: "logout"}, controllers: {sessions: "admin/sessions"}

  resources :people, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get ':featured_topic', action: 'featured_topic', as: 'featured_topic', featured_topic: /on-.+/, format: true
      get 'facebook'
      get 'pinterest'
      get 'twitter'
      get 'google_plus'
      get ':redirect_to_person', action: 'redirect_to_person', constraints: { page: /\D+/ }
    end
  end

  resources :proverbs, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end
    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get ':featured_topic', action: 'featured_topic', as: 'featured_topic', featured_topic: /on-.+/, format: true
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
      get ':redirect_to_proverb', action: 'redirect_to_proverb', constraints: { page: /\D+/ }
    end
  end

  resources :books, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
      get ':redirect_to_book', action: 'redirect_to_book', constraints: { page: /\D+/ }
    end
  end

  namespace :topics do
    resources :topic_combinations, path: "combinations", only: [:index, :show] do
      member do
        get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
        get 'pinterest'
        get 'facebook'
        get 'twitter'
        get 'google_plus'
      end
    end
  end

  resources :topics, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :movies, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :tv_shows, only: [:index, :show], path: "tv-shows" do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :characters, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :quotes, only: [] do
    member do
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :messages, path: "contact-us", only: [:new, :create] do
    collection do
      get "success", action: "success", as: "success"
    end
  end
  resources :subscribers, only: [:create]

  get 'feed' => 'welcome#feed', :as => :feed
  get 'privacy-policy' => 'static_pages#privacy_policy', as: :privacy_policy
	get 'about-us' => 'static_pages#about_us', as: :about_us
	get 'disclaimer' => 'static_pages#disclaimer', as: :disclaimer
	get 'terms-and-conditions' => 'static_pages#terms_and_conditions', as: :terms_and_conditions

  get "/404" => "exceptions#serve_404", as: "serve_404"

  get "/500" => "exceptions#serve_500"

  root 'welcome#index'

  namespace :admin do
    root 'dashboard#index'
    get "regenerate-social-images" => "dashboard#regenerate_social_images", as: :regenerate_social_images
    get "regenerate-quote-images" => "dashboard#regenerate_quote_images", as: :regenerate_quote_images
    
    resources :users, only: [:index, :destroy]
    resources :subscribers, only: [:index, :destroy]
    
    resources :quotes do
      member do
        get "verify"
        get "tweetable"
        get "image"
      end
    end
    resources :people do
      member do
        get "review"
        get ':featured_topic', action: 'featured_topic', as: 'featured_topic', featured_topic: /on-.*/
      end
    end
    resources :books do
      member do
        get "review"
      end
    end
    resources :movies do
      member do
        get "review"
      end
    end
    resources :proverbs do
      member do
        get "review"
      end
    end
    resources :tv_shows, path: "tv-shows" do
      member do
        get "review"
      end
    end
    resources :characters do
      member do
        get "review"
      end
    end

    resources :featured_topics
    resources :topics do
      member do
        get "review"
      end
      resources :topic_aliases
    end
    resources :topic_combinations, only: [:index, :show], path: "topic-combinations"
    resources :quote_topic_suggestions, only: [:index], path: "quote-topic-suggestions" do
      member do
        get 'accept', as: 'accept'
        get 'decline', as: 'decline'
      end
    end
    resources :tweetable_quotes, path: "tweetable-quotes", only: [:index, :destroy]
    resources :quote_of_the_days, path: "quote-of-the-day", only: [:index]
    resources :color_schemes, path: "color-schemes"
    resources :messages, only: [:index, :show, :destroy]
    resources :logs, only: [:index, :destroy]
    resources :redirects, except: [:show]
    resources :settings
    resources :nationalities
    resources :professions
  end

  namespace :my do
    root "dashboard#index"
    get "mark-for-deletion" => "dashboard#mark_for_deletion", as: :account_mark_for_deletion
    get "unmark-for-deletion" => "dashboard#unmark_for_deletion", as: :account_unmark_for_deletion
    resources :user_lists, path: "lists"
    resources :user_quotes, path: "quotes", except: [:show]
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
    include PgSearch
    include Loggable
    include Searchable
    include Seoable
    include Imageable    
    include SocialImageable
    include TimeLineable
    include SearchSuggestable
    include Reviewable

    pg_search_scope :search_by_name, against: :name, using: { tsearch: {prefix: true} }

    has_one :time_line, as: :item, dependent: :destroy
    has_many :quote_topics, dependent: :destroy
    has_many :quotes, through: :quote_topics
    has_many :topic_aliases, dependent: :destroy
    accepts_nested_attributes_for :topic_aliases, reject_if: :all_blank, allow_destroy: true
    has_many :topic_combinations, foreign_key: "primary_topic_id", dependent: :destroy
    accepts_nested_attributes_for :topic_combinations, reject_if: :all_blank, allow_destroy: true
    has_many :quote_topic_suggestions, dependent: :destroy

    # name should be present and unique
    # slug should be present and unique
    validates :name, presence: true, uniqueness:true, blank: false
    validates :slug, presence: true, uniqueness:true, blank: false

    scope :published, -> {where(published: true)}
    scope :draft, -> {where(published: false)}
    scope :popular, -> {where(popular: true)}
    scope :very_popular, -> {where(very_popular: true)}
    scope :by_alphabet, ->(alphabet) {where('name like ?', "#{alphabet}%")}

    after_create :get_quote_suggestions

    def to_param
        slug
    end

    def get_quote_suggestions
        Delayed::Job.enqueue SuggestTopicQuotesJob.new(self.id)
    end

    def add_to_time_line
        TimeLine.create(item: self) if self.published
    end

    def all_topic_combinations
        pt = TopicCombination.where(primary_topic_id: self.id).pluck(:id)
        st = TopicCombination.where(secondary_topic_id: self.id).pluck(:id)
        TopicCombination.where(id: pt + st)
    end

    def self.cached_very_popular
        Rails.cache.fetch("very_popular_topic") do
            very_popular.published.order(name: "ASC").to_a
        end
    end

    def expire_cache
        Rails.cache.delete("very_popular_topic") if self.very_popular? && self.very_popular_changed?
    end
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController
  before_filter :authenticate_admin!
  before_action :set_topic, only: [:show, :edit, :update, :destroy, :review]

  # GET /topics
  # GET /topics.json
  def index
    if params[:search].present?
      if params[:status].present?
        case params[:status]
        when "Draft"
          @topics = Topic.draft.search_by_name(params[:search]).order(name: :ASC).page params[:page]
        when "Published"
          @topics = Topic.published.search_by_name(params[:search]).order(name: :ASC).page params[:page]
        end
      else
        @topics = Topic.search_by_name(params[:search]).order(name: :ASC).page params[:page]
      end
    else
      if params[:status].present?
        case params[:status]
        when "Draft"
          @topics = Topic.draft.order(name: :ASC).page params[:page]
        when "Published"
          @topics = Topic.published.order(name: :ASC).page params[:page]
        end
      else
        @topics = Topic.order(name: :ASC).page params[:page]
      end
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
    @topic.build_seo if @topic.seo.nil?
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to admin_topic_url(@topic), notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to admin_topic_url(@topic), notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def review
    @review = @topic.review || @topic.build_review
    @review.date = Date.today
    @review.save
    redirect_to admin_topic_path(@topic)
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to admin_topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :byline, :slug, :popular, :very_popular, :published, topic_combinations_attributes: [:id, :secondary_topic_id, :_destroy], seo_attributes: [:id, :title, :description, :_destroy], topic_aliases_attributes: [:id, :name, :_destroy])
    end
end

app/controllers/topics/topic_combinations_controller.rb
class Topics::TopicCombinationsController < ApplicationController
  before_action :set_topic_combination, only: [:show, :twitter, :facebook, :pinterest]
  
  def index
    @topics = TopicCombination.order(slug: "ASC").group_by{|a| a.name[0]}
  end

  def show
    if params[:search].present?
      UserSearchWorker.perform_async(@topic_combination.class.name, @topic_combination.id, params[:search])
      @quotes = @topic.quotes.search_by_text(params[:search]).order(total_share_count: :desc).order(text: :asc).page params[:page]
    else
      @quotes = @topic.quotes.order(total_share_count: :desc).order(text: :asc).page params[:page]
    end
  end
  
  def alphabet
    @alphabet = params[:alphabet].upcase
    @topic_combination_combinations = topic_combination.by_alphabet(@alphabet).published.order(name: "ASC")
    @canonical = alphabet_topic_topic_combinations_url
  end
  
  def twitter
    url = URI.encode(topics_topic_combination_url(@topic))
    text = CGI::escape("#{@topic.name} Quotes")
    redirect_to "https://twitter.com/intent/tweet?text=#{text}&amp;url=#{url}&amp;via=DoYouLoveAQuote"
  end
  
  def facebook
    url = URI.encode(topics_topic_combination_url(@topic))
    redirect_to "https://www.facebook.com/sharer/sharer.php?u=#{url}"
  end
  
  def pinterest
    url = URI.encode(topics_topic_combination_url(@topic))
    media = URI.encode(@author.image_url(:large))
    redirect_to "http://www.pinterest.com/pin/create/topic_combinationmarklet/?url=#{url}&amp;media=#{media}&amp;description=#{description}"
  end
  
  private
  
  def set_topic_combination
      @topic = TopicCombination.find_by_slug(params[:id])
      if ! @topic
        @redirect = Redirect.find_by_from(topics_topic_combination_path(id: params[:id]))
        if ! @redirect
          NotFoundWorker.perform_async(topics_topic_combination_path(id: params[:id]), request.user_agent)
          redirect_to serve_404_url
        else
          redirect_to @redirect.to, status: 301
        end
      end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :twitter, :facebook, :pinterest]

  def index
    @topics = Topic.popular.published.order(name: "ASC").group_by{|a| a.name[0]}
    @canonical = topics_url
  end

  def show
    @quotes = @topic.quotes.order(total_share_count: :desc).order(text: :asc).page params[:page]
  end

  def alphabet
    @alphabet = params[:alphabet].upcase
    @topics = Topic.by_alphabet(@alphabet).published.order(name: "ASC")
    @canonical = alphabet_topics_url
  end

  def twitter
    url = URI.encode(topic_url(@topic))
    text = CGI::escape("#{@topic.name} Quotes")
    redirect_to "https://twitter.com/intent/tweet?text=#{text}&amp;url=#{url}&amp;via=DoYouLoveAQuote"
  end

  def facebook
    url = URI.encode(topic_url(@topic))
    redirect_to "https://www.facebook.com/sharer/sharer.php?u=#{url}"
  end

  def pinterest
    url = URI.encode(topic_url(@topic))
    media = URI.encode(@topic.social_image.pinterest_url)
    description = CGI::escape(@topic.name +  ' #quotes')
    redirect_to "http://www.pinterest.com/pin/create/topicmarklet/?url=#{url}&amp;media=#{media}&amp;description=#{description}"
  end

  def feed
    @timelines = TimeLine.where(item_type: "Topic").order(created_at: :DESC).limit(20)
    respond_to do |format|
      format.html { redirect_to feed_url, status: 301 }
      format.rss { render layout: false }
    end
  end
  private

  def set_topic
      @topic = Topic.published.find_by_slug(params[:id])
      if ! @topic
        @redirect = Redirect.find_by_from(topic_path(id: params[:id]))
        if ! @redirect
          Delayed::Job.enqueue NotFoundJob.new(topic_path(id: params[:id]), request.user_agent)
          redirect_to serve_404_url
        else
          redirect_to @redirect.to, status: 301
        end
      end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/admin/topics/_topic_alias_fields.html.erb
<div class='nested-fields'>
    <%= f.input :name %>
    <%= link_to_remove_association '<i class="e-icon-squared-cross"></i>'.html_safe, f %>
</div>

app/views/admin/topics/_topic_combination_fields.html.erb
<div class='nested-fields'>
    <%= f.input :secondary_topic_id, as: :select, collection: Topic.all.order(name: :asc) %>
    <%= link_to_remove_association '<i class="e-icon-squared-cross"></i>'.html_safe, f %>
</div>

app/views/admin/topics/edit.html.erb
<% content_for :content do %>
<div class="col-sm-12">
    <h2>Edit <%= link_to "topic", admin_topic_url(@topic), class: "btn btn-default btn-sm" %> <%= link_to "Delete", admin_topic_url(@topic), method: :delete, class: "btn btn-danger btn-sm" %></h2>
    <%= render 'form' %>
</div>
<% end %>

app/views/admin/topics/index.html.erb
<% content_for :content do %>
<div class="col-sm-12">
  <div class="row">
    <div class="col-sm-9">
      <div class="row">
        <div class="col-sm-6">
          <h2 style="margin-top: 0px">Topic <%= link_to "add new", new_admin_topic_url, class: "btn btn-default btn-sm" %></h2>
        </div>
        <div class="col-sm-6" style="margin-bottom: 10px;">
          <%= form_tag "", method: :get, class: "form-inline", style: "float:right" do %>
           <div class="form-group">
            <%= text_field_tag :search, params[:search], class: "form-control" %>
            <%= hidden_field_tag :stauts, params[:status] %>
            <%= submit_tag "Search", class: "btn" %>
            </div>
          <% end %>          
          
          <%= form_tag "", method: :get, style: "width:35%; float:right; padding-right: 10px;" do %>
            <%= select_tag "status", options_for_select(["Draft", "Published"], params[:status]), prompt: "Filter by Status", onchange: "this.form.submit()", class: "form-control" %>
            <%= hidden_field_tag :search, params[:search] %>
          <% end %>          
        </div>
      </div>
  
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th width="70%" class="text-center">Name</th>
            <th width="20%" class="text-center">Status</th>
            <th width="10%" class="text-center" colspan="2">Manage</th>
          </tr>
        </thead>
      
        <tbody>
          <% @topics.each do |topic| %>
            <tr>
              <td style="vertical-align: middle"><%= topic.name %></td>
              <td class="text-center"><%= topic.published? ? "Published" : "Draft" %></td>
              <td class="text-center" style="vertical-align: middle"><%= link_to '<i class="fa fa-arrow-right"></i>'.html_safe, admin_topic_url(topic) %></td>
              <td class="text-center" style="vertical-align: middle"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_admin_topic_url(topic) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="text-center">
        <%= paginate @topics, :views_prefix => 'kaminari_bootstrap' %>
      </div>
    </div>
    
    <div class="col-sm-3">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <div class="panel-title">
            Recently Added
          </div>
        </div>
        <div class="panel-body">
          <table class="table table-striped table-bordered table-hover">
            <tbody>
              <% Topic.order(created_at: :DESC).limit(5).each do |topic| %>
                <tr>
                  <td><%= topic.name %></td>
                  <td class="text-center"><%= link_to "View", admin_topic_url(topic) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/admin/topics/new.html.erb
<% content_for :content do %>
<div class="col-sm-12">
    <h2>Add New <%= link_to "back", admin_topics_url, class:"btn btn-sm btn-default" %></h2>
    <%= render 'form' %>
</div>
<% end %>

app/views/admin/topics/show.html.erb
<% content_for :content do %>
<div class="col-sm-12">
  <ol class="breadcrumb bc-3">
    <li><%= link_to "Home", admin_root_url %></li>
    <li><%= link_to "Topics", admin_topics_url %></li>
    <li class="active"><%= @topic.name %></li>
  </ol>

  <div class="row">
    <div class="col-sm-9">
      <h2><%= @topic.name %> <%= link_to "view", topic_url(@topic), class: "btn btn-default btn-sm", target: "_blank" %> <%= link_to "edit", edit_admin_topic_url(@topic), class: "btn btn-default btn-sm" %></h2>

      <div class="panel minimal minimal-gray">

        <div class="panel-heading">
          <div class="panel-title">
          </div>
          <div class="panel-options">
            <ul class="nav nav-tabs">
              <li class="active"><a href="#quotes" data-toggle="tab" aria-expanded="true">Quotes</a></li>
              <li class=""><a href="#quote-suggestions" data-toggle="tab" aria-expanded="false">Quote Suggestions</a></li>
              <% if @topic.social_image.present? %>
                <li><a href="#social-image" data-toggle="tab">Social Images</a></li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="panel-body">
          <div class="tab-content">
            <div class="tab-pane active" id="quotes">
              <table class="table table-striped table-bordered table-hover">
                <thead>
                  <tr>
                    <th width="5%" class="text-center">Verified</th>
                    <th width="60%" class="text-center">Quote</th>
                    <th width="20%" class="text-center">Source</th>
                    <th width="20%" class="text-center" colspan="6">Manage</th>
                  </tr>
                </thead>

                <tbody>
                    <% @topic.quotes.order(text: :ASC).each do |quote| %>
                        <tr>
                          <td class="text-center"><%= quote.verified ? '<i class="fa fa-check"></i>'.html_safe : '<i class="fa fa-times"></i>'.html_safe %></td>
                          <td><%= quote.text %></td>
                          <td class="text-center"><%= link_to quote.source.name, admin_quote_source_url(quote) %></td>
                          <td class="text-center"><%= link_to '<i class="fa fa-picture-o"></i>'.html_safe, image_admin_quote_url(quote), remote: true, "data-type": "json", class: "image-quote" %></td>
                          <td class="text-center"><%= link_to '<i class="fa fa-twitter"></i>'.html_safe, tweetable_admin_quote_url(quote), remote: true, "data-type": "json", class: "tweetable-quote" %></td>
                          <td class="text-center"><%= link_to '<i class="fa fa-calendar"></i>'.html_safe, qotd_admin_quote_url(quote), remote: true, "data-type": "json", class: "qotd-quote" %></td>
                          <td class="text-center"><%= link_to '<i class="fa fa-check"></i>'.html_safe, verify_admin_quote_url(quote), remote: :true, "data-type": "json", class: "verify-quote" %></td>
                          <td class="text-center"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_admin_quote_url(quote), target: "_blank" %></td>
                          <td class="text-center"><%= link_to '<i class="fa fa-trash"></i>'.html_safe, admin_quote_url(quote), method: :delete, remote: true, class: "delete-quote" %></td>                          
                        </tr>
                    <% end %>
                </tbody>
              </table>
            </div>
            
            <div class="tab-pane" id="quote-suggestions">
              <table class="table table-striped table-bordered table-hover">
                <thead>
                  <tr>
                    <th width="65%" class="text-center">Quote</th>
                    <th width="20%" class="text-center">Source</th>
                    <th width="15%" class="text-center" colspan="3">Manage</th>
                  </tr>
                </thead>
              
                <tbody>
                  <% @topic.quote_topic_suggestions.where(read: false).order(quote_id: :ASC).each do |quote_topic_suggestion| %>
                    <tr>
                      <td><%= quote_topic_suggestion.quote.text %></td>
                      <td class="text-center"><%= link_to quote_topic_suggestion.quote.source.name, admin_quote_source_url(quote_topic_suggestion.quote) %> <%= quote_topic_suggestion.quote.source.published ? '<span class="badge badge-default">P</span>'.html_safe : '<span class="badge badge-default">D</span>'.html_safe %></td>
                      <td class="text-center"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_admin_quote_url(quote_topic_suggestion.quote), target: "_blank" %></td>
                      <td class="text-center"><%= link_to '<i class="fa fa-check"></i>'.html_safe, accept_admin_quote_topic_suggestion_url(id: quote_topic_suggestion.id), class:"accept_suggestion", remote: true %></td>
                      <td class="text-center"><%= link_to '<i class="fa fa-times"></i>'.html_safe, decline_admin_quote_topic_suggestion_url(id: quote_topic_suggestion.id), class:"decline_suggestion", remote: true %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>

            <% if @topic.social_image.present? %>
              <div class="tab-pane" id="social-image">
                <h4>Facebook</h4>
                <%= image_tag @topic.social_image.facebook, style: "max-width: 100%" %>

                <h4>Twitter</h4>
                <%= image_tag @topic.social_image.twitter, style: "max-width: 100%" %>

                <h4>Google Plus</h4>
                <%= image_tag @topic.social_image.google_plus, style: "max-width: 100%" %>

                <h4>Pinterest</h4>
                <%= image_tag @topic.social_image.pinterest, style: "max-width: 100%" %>
              </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-3">
      <%= render partial: "admin/partials/review", locals: {model: @topic} %>

      <% if @topic.topic_combinations.any? %>
        <div class="panel panel-default panel-shadow">
          <div class="panel-heading">
            <div class="panel-title">
              <h4>Combinations</h4>
            </div>
          </div>
          <div class="panel-body">
            <ul>
              <% @topic.all_topic_combinations.each do |combination| %>
                <li><%= link_to combination.primary_topic.name + " and " + combination.secondary_topic.name, admin_topic_combination_path(combination) %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    $(".accept_suggestion")
    .on("ajax:complete", function(e, data, status, xhr) {
        $(this).closest("tr").remove();
    });
  
    $(".decline_suggestion")
    .on("ajax:complete", function(e, data, status, xhr) {
        $(this).closest("tr").remove();
    });
    
    $(".delete-quote").on("ajax:complete", function(xhr, status) {
      $(this).closest("tr").remove();
    });
    
    $(".qotd-quote").on("ajax:complete", function(xhr, status) {
      toastr.success('Quote added to Quote of The Day queue.');
    });    
    
    $(".image-quote").on("ajax:complete", function(xhr, status) {
      toastr.success('Image generate started for quote.');
    });      
    
    $(".tweetable-quote").on("ajax:success", function(data, status, xhr) {
      toastr.success('Quote added to TweetableQuote list.');
    });
    
    $(".tweetable-quote").on("ajax:error", function(xhr, status, error) {
      toastr.error('Oops! this quote could not be added to TweetableQuote list.');
    });    
    
    $(".verify-quote").on("ajax:complete", function(e, data, status, xhr) {
      var response = jQuery.parseJSON(data.responseText);
      if (response.verification_status) {
        $(this).parent().siblings().first().children("i").attr('class', 'fa fa-check');
        toastr.success('Quote marked as verified.');
      } else {
        $(this).parent().siblings().first().children("i").attr('class', 'fa fa-times');
        toastr.warning('Quote marked as unverified.');
      }
    });        
  });
</script>
<% end %>