config/routes.rb
Rails.application.routes.draw do
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]  
  get 'static_pages/privacy_policy'
  get 'static_pages/about_us'
  get 'static_pages/disclaimer'
  get 'static_pages/terms_and_conditions'

  get "system/*path", to: redirect("/", status: 301)
  get "pictures", to: redirect("/", status: 301)
  get "pictures/*path", to: redirect("/", status: 301)
  get "quote-of-the-day", to: redirect("/", status: 301)
  get "quote-of-the-day/*path", to: redirect("/", status: 301)
  get "authors", to: redirect("/people", status: 301)
  get "authors/:slug", to: redirect("/people/%{slug}", status: 301)
  get "authors/:slug/:page", to: redirect("/people/%{slug}/%{page}", status: 301)

  devise_for :users, path: "my", controllers: {omniauth_callbacks: "my/omniauth_callbacks"}
  devise_scope :user do
    get 'login', :to => 'my/sessions#new', :as => :new_user_session
    get 'logout', :to => 'my/sessions#destroy', :as => :destroy_user_session
  end
  
  devise_for :admins, path: "admin", path_names: {sign_in: "login", sign_out: "logout"}, controllers: {sessions: "admin/sessions"}

  resources :people, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get ':featured_topic', action: 'featured_topic', as: 'featured_topic', featured_topic: /on-.+/, format: true
      get 'facebook'
      get 'pinterest'
      get 'twitter'
      get 'google_plus'
      get ':redirect_to_person', action: 'redirect_to_person', constraints: { page: /\D+/ }
    end
  end

  resources :proverbs, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end
    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get ':featured_topic', action: 'featured_topic', as: 'featured_topic', featured_topic: /on-.+/, format: true
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
      get ':redirect_to_proverb', action: 'redirect_to_proverb', constraints: { page: /\D+/ }
    end
  end

  resources :books, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
      get ':redirect_to_book', action: 'redirect_to_book', constraints: { page: /\D+/ }
    end
  end

  namespace :topics do
    resources :topic_combinations, path: "combinations", only: [:index, :show] do
      member do
        get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
        get 'pinterest'
        get 'facebook'
        get 'twitter'
        get 'google_plus'
      end
    end
  end

  resources :topics, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :movies, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :tv_shows, only: [:index, :show], path: "tv-shows" do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :characters, only: [:index, :show] do
    collection do
      get ':alphabet', action: 'alphabet', as: 'alphabet', alphabet: /[A-Z]/
      get 'feed'
    end

    member do
      get ':page', action: 'show', constraints: { page: /\d+/ }, as: 'page'
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :quotes, only: [] do
    member do
      get 'pinterest'
      get 'facebook'
      get 'twitter'
      get 'google_plus'
    end
  end

  resources :messages, path: "contact-us", only: [:new, :create] do
    collection do
      get "success", action: "success", as: "success"
    end
  end
  resources :subscribers, only: [:create]

  get 'feed' => 'welcome#feed', :as => :feed
  get 'privacy-policy' => 'static_pages#privacy_policy', as: :privacy_policy
	get 'about-us' => 'static_pages#about_us', as: :about_us
	get 'disclaimer' => 'static_pages#disclaimer', as: :disclaimer
	get 'terms-and-conditions' => 'static_pages#terms_and_conditions', as: :terms_and_conditions

  get "/404" => "exceptions#serve_404", as: "serve_404"

  get "/500" => "exceptions#serve_500"

  root 'welcome#index'

  namespace :admin do
    root 'dashboard#index'
    get "regenerate-social-images" => "dashboard#regenerate_social_images", as: :regenerate_social_images
    get "regenerate-quote-images" => "dashboard#regenerate_quote_images", as: :regenerate_quote_images
    
    resources :users, only: [:index, :destroy]
    resources :subscribers, only: [:index, :destroy]
    
    resources :quotes do
      member do
        get "verify"
        get "tweetable"
        get "image"
      end
    end
    resources :people do
      member do
        get "review"
        get ':featured_topic', action: 'featured_topic', as: 'featured_topic', featured_topic: /on-.*/
      end
    end
    resources :books do
      member do
        get "review"
      end
    end
    resources :movies do
      member do
        get "review"
      end
    end
    resources :proverbs do
      member do
        get "review"
      end
    end
    resources :tv_shows, path: "tv-shows" do
      member do
        get "review"
      end
    end
    resources :characters do
      member do
        get "review"
      end
    end

    resources :featured_topics
    resources :topics do
      member do
        get "review"
      end
      resources :topic_aliases
    end
    resources :topic_combinations, only: [:index, :show], path: "topic-combinations"
    resources :quote_topic_suggestions, only: [:index], path: "quote-topic-suggestions" do
      member do
        get 'accept', as: 'accept'
        get 'decline', as: 'decline'
      end
    end
    resources :tweetable_quotes, path: "tweetable-quotes", only: [:index, :destroy]
    resources :quote_of_the_days, path: "quote-of-the-day", only: [:index]
    resources :color_schemes, path: "color-schemes"
    resources :messages, only: [:index, :show, :destroy]
    resources :logs, only: [:index, :destroy]
    resources :redirects, except: [:show]
    resources :settings
    resources :nationalities
    resources :professions
  end

  namespace :my do
    root "dashboard#index"
    get "mark-for-deletion" => "dashboard#mark_for_deletion", as: :account_mark_for_deletion
    get "unmark-for-deletion" => "dashboard#unmark_for_deletion", as: :account_unmark_for_deletion
    resources :user_lists, path: "lists"
    resources :user_quotes, path: "quotes", except: [:show]
  end
end

app/models/quote.rb
class Quote < ActiveRecord::Base
    include ActionView::Helpers::TextHelper
    include PgSearch
    include Loggable
    include SocialImageable
    
    has_attached_file :image, 
        styles: { medium: "600x600>" },
        url: "/uploads/:class/:id/:slug_:style.:extension",
        path: ":rails_root/public:url"
        
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    
    Paperclip.interpolates :slug  do |attachment, style|
        attachment.instance.slug
    end
    
    pg_search_scope :search_by_text, against: :text, using: { tsearch: {prefix: true} }

    # belongs to source
    belongs_to :source, polymorphic: true, touch: true
    belongs_to :character

    has_many :quote_topics, dependent: :destroy
    accepts_nested_attributes_for :quote_topics, reject_if: :all_blank, allow_destroy: true

    has_many :topics, through: :quote_topics
    has_many :quote_topic_suggestions, dependent: :destroy

    has_many :quote_of_the_days, dependent: :destroy
    has_many :tweetable_quotes, dependent: :destroy
    has_many :user_quotes, dependent: :destroy

    # text should be present and unique
    validates :text, presence: true, uniqueness: true
    validates :source_id, presence: true
    validates :source_type, presence: true

    before_validation :strip_text, :generate_slug
    after_save :get_topic_suggestions

    def strip_text
        self.text = self.text.strip
    end
    
    def generate_slug
        unless self.slug.present?
            case self.source.class.name
            when "Person"
                quote_length = 70 - self.source.name.length - 4
            when "Book"
                quote_length = 70 - self.source.name.length - 6
            when "Movie"
                quote_length = 70 - self.source.name.length - 6
            when "TvShow"
                quote_length = 70 - self.source.name.length - 6
            when "Proverb"
                quote_length = 70 - (self.source.name + " Proverb").length - 3
            end
            slug = truncate(self.text, length: quote_length, separator: ' ').tr('.','')
            self.slug = slug.to_url
        end
    end

    def get_topic_suggestions
        Delayed::Job.enqueue SuggestTopicsJob.new(self.id)
    end
    
    scope :verified, -> {where(verified: true)}
    scope :filter_by_topic, -> (id) {joins(:quote_topics).where(quote_topics: {topic_id: id})}
    
    scope :with_image, -> (count) { where(image_width: 1200, image_height: 600).order(created_at: :DESC).limit(count) }
    
    def self.cached_with_image(count)
        Rails.cache.fetch("quotes-with-images-#{count.to_s}-#{Date.today.to_s(:number)}") do
            with_image(count)
        end
    end
end

app/controllers/admin/quotes_controller.rb
class Admin::QuotesController < ApplicationController
  before_filter :authenticate_admin!
  before_action :set_quote, only: [:edit, :update, :destroy, :verify, :tweetable, :image]

  def index
    if params[:search].present?
      @quotes = Quote.search_by_text(params[:search]).page params[:page]
    else
      @quotes = Quote.order(created_at: :DESC).page params[:page]
    end
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end
  
  def verify
    respond_to do |format|
      ActiveRecord::Base.no_touching do
        if @quote.toggle!(:verified)
          format.json {render json: {verification_status: @quote.verified}}
        end
      end
    end
  end
  
  def tweetable
    @tweetable_quote = TweetableQuote.new(quote: @quote)
    if @tweetable_quote.save
      respond_to  do |format|
        format.json { render json: @tweetable_quote, status: :ok }
      end
    else
      respond_to  do |format|
        format.json { render json: @tweetable_quote.errors, status: :unprocessable_entity }
      end      
    end
  end

  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html {
          if params[:quote][:redirect_to].present?
            redirect_to params[:quote][:redirect_to], notice: 'Quote was successfully created.'
          else
            redirect_to view_context.admin_model_url(@quote.source), notice: 'Quote was successfully created.'
          end
        }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html {
          if params[:quote][:redirect_to].present?
            redirect_to params[:quote][:redirect_to], alert: 'Oops! an error occurred while creating the quote.'
          else
            redirect_to view_context.admin_model_url(@quote.source), alert: 'Oops! an error occurred while creating the quote.'
          end
        }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to edit_admin_quote_url(@quote), notice: 'Quote was successfully updated.' }
        format.json { render json: @quote, status: :ok }
      else
        format.html { redirect_to view_context.admin_model_url(@quote.source), notice: 'Oops! an error occurred while updating the quote.' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    head :ok
  end

  def image
    Delayed::Job.enqueue QuoteImageJob(@quote.id)
    #Delayed::Job.enqueue QuoteSocialImageJob.new(@quote.id)
    respond_to do |format|
      format.json { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:text, :verified, :character_id, :source_id, :source_type, :topic_ids => [], quote_topics_attributes: [:id, :topic_id, :_destroy])
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:pinterest, :facebook, :twitter, :google_plus]

  def twitter
    unless current_admin
      QuoteTwitterWorker.perform_async(@quote.id, request.user_agent) if params[:human].present? && params[:human] == "t"
    end  
    url = URI.encode(view_context.quote_source_url(@quote))
    text = CGI::escape(view_context.truncate(@quote.text, length: (140 - 22 - 23), seperator: " "))

    redirect_to "https://twitter.com/intent/tweet?text=#{text}&amp;url=#{url}&amp;via=DoYouLoveAQuote"
  end

  def facebook
    unless current_admin
      QuoteFacebookWorker.perform_async(@quote.id, request.user_agent) if params[:human].present? && params[:human] == "t"
    end
    url = URI.encode(view_context.quote_source_url(@quote))
    redirect_to "https://www.facebook.com/sharer/sharer.php?u=#{url}"
  end

  def pinterest
    unless current_admin
      QuotePinterestWorker.perform_async(@quote.id, request.user_agent) if params[:human].present? && params[:human] == "t"
    end
    url = URI.encode(view_context.quote_source_url(@quote))
    media = URI.encode(@quote.social_image.pinterest.url)
    description = CGI::escape(@quote.text + ' - ' + @quote.source.name +  ' #quotes')
    redirect_to "http://www.pinterest.com/pin/create/bookmarklet/?url=#{url}&amp;media=#{media}&amp;description=#{description}"
  end

  private

  def set_quote
    @quote = Quote.find(params[:id])
  end
end

app/views/admin/quotes/_form.html.erb
<%= simple_form_for([:admin, @quote],
  html: { class: 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  }) do |f| %>
  <div class="row">
    <div class="col-sm-9">
    <div class="panel minimal minimal-gray">
      <div class="panel-heading">
        <div class="panel-title">

        </div>
        <div class="panel-options">
          <ul class="nav nav-tabs">
            <li class="active"><a href="#quote" data-toggle="tab">Quote</a></li>
            <li><a href="#quote-seo" data-toggle="tab">Quote SEO</a></li>
            <li><a href="#quote-topics" data-toggle="tab">Topics</a></li>

            <% if @quote.quote_topic_suggestions.where(read: false)  .any? %>
              <li><a href="#quote-topic-suggestions" data-toggle="tab">Topic Suggestions</a></li>
            <% end %>

            <% if (@quote.source_type == "Book" || @quote.source_type == "TvShow" || @quote.source_type == "Movie") && @quote.source.characters.present? %>
              <li><a href="#quote-character" data-toggle="tab">Quote Character</a></li>
            <% end %>
            
            <% if @quote.image.present? %>
              <li><a href="#quote-image" data-toggle="tab">Quote Image</a></li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="panel-body">
        <div class="tab-content">
          <div class="tab-pane active" id="quote">
            <div class="form-inputs">
              <%= f.input :text, input_html: {rows: 5} %>
              <%= f.input :verified %>
            </div>
          </div>
          
          <div class="tab-pane" id="quote-seo">
            <div class="form-inputs">
              <%= f.input :slug %>
            </div>
          </div>

          <div class="tab-pane" id="quote-topics">
            <div id='quote_topics'>
              <%= f.simple_fields_for :quote_topics do |quote_topic| %>
                <%= render 'quote_topic_fields', :f => quote_topic %>
              <% end %>
              <div class='links'>
                <%= link_to_add_association '<i class="fa fa-plus-square"></i> topic'.html_safe, f, :quote_topics %>
              </div>
            </div>
          </div>

          <% if @quote.quote_topic_suggestions.any? %>
            <div class="tab-pane" id="quote-topic-suggestions">
              <div id='quote_topic_suggestions'>
                <table class="table table-striped table-bordered table-hover">
                  <thead>
                    <tr>
                      <th width="60%" class="text-center">Topic</th>
                      <th width="40%" class="text-center" colspan="2">Manage</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @quote.quote_topic_suggestions.where(read: false).each do |quote_topic_suggestion| %>
                      <tr>
                        <td class="text-center"><%= link_to quote_topic_suggestion.topic.name, admin_topic_url(quote_topic_suggestion.topic) %></td>
                        <td class="text-center"><%= link_to '<i class="fa fa-check"></i>'.html_safe, accept_admin_quote_topic_suggestion_url(id: quote_topic_suggestion.id), class:"accept_suggestion", remote: true %></td>
                        <td class="text-center"><%= link_to '<i class="fa fa-times"></i>'.html_safe, decline_admin_quote_topic_suggestion_url(id: quote_topic_suggestion.id), class:"decline_suggestion", remote: true %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>

            <script type="text/javascript">
              $(function() {
                $(".accept_suggestion")
                .on("ajax:complete", function(e, data, status, xhr) {
                    $(this).closest("tr").remove();
                });

                $(".decline_suggestion")
                .on("ajax:complete", function(e, data, status, xhr) {
                    $(this).closest("tr").remove();
                });
              });
            </script>
          <% end %>

          <% if (@quote.source_type == "Book" || @quote.source_type == "TvShow" || @quote.source_type == "Movie") && @quote.source.characters.present? %>
            <div class="tab-pane" id="quote-character">
              <%= f.association :character, collection: @quote.source.characters.order(name: :asc) %>
            </div>
          <% end %>
          
          <% if @quote.image.present? %>
            <div class="tab-pane" id="quote-image">
              <%= image_tag @quote.image.medium.url %>
            </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>

  <div class="col-sm-3 text-center">
    <% if @quote.errors.any? %>
      <div class="alert alert-danger">
        <%= "#{@quote.errors.count} error found" %>
      </div>
    <% end %>
    <%= f.button :submit %>
  </div>
</div>

<% end %>

app/views/admin/quotes/_quoted_in_book_fields.html.erb
<div class='nested-fields'>
    <%= f.input :name %>
    <%= f.input :author %>
    <%= f.input :chapter %>
    <%= f.input :page %>
    <%= link_to_remove_association '<i class="e-icon-squared-cross"></i>'.html_safe, f %>
</div>

app/views/admin/quotes/edit.html.erb
<% content_for :content do %>
<div class="col-sm-12">
    <ol class="breadcrumb bc-3"> 
    <li><%= link_to "Home", admin_root_url %></li>
    <li><%= link_to @quote.source.name, admin_model_url(@quote.source) %></li> 
    <li class="active"><%= truncate @quote.text %></li>
    </ol>    
    <h2>Edit</h2>
    <%= render "form" %>
</div>
<% end %>

app/views/admin/quotes/index.html.erb
<% content_for :content do %>
<div class="col-sm-12">
  <div class="row">
    <div class="col-sm-6">
      <h2 style="margin-top: 0px">Quote <%= link_to "add new", new_admin_quote_url, class: "btn btn-default btn-sm" %></h2>
    </div>
    <div class="col-sm-6" style="margin-bottom: 10px;">
      <%= form_tag "", method: :get, class: "form-inline", style: "float:right" do %>
       <div class="form-group">
        <%= text_field_tag :search, params[:search], class: "form-control" %>
        <%= submit_tag "Search", class: "btn" %>
        </div>
      <% end %>          
    </div>
  </div>

  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th width="60%" class="text-center">Text</th>
        <th width="25%" class="text-center">Source</th>
        <th width="15%" class="text-center" colspan="2">Manage</th>
      </tr>
    </thead>
  
    <tbody>
      <% @quotes.each do |quote| %>
        <tr>
          <td><%= quote.text %></td>
          <td><%= link_to quote.source.name, admin_model_url(quote.source) %></td>
          <td class="text-center"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_admin_quote_url(quote) %></td>
          <td class="text-center"><%= link_to '<i class="fa fa-times"></i>'.html_safe, admin_quote_url(quote) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center">
    <%= paginate @quotes, :views_prefix => 'kaminari_bootstrap' %>
  </div>
</div>
<% end %>